---
- hosts: all
  become: yes
  tasks:
  - name: install apache server
    package:
      name: "{{ pack_name }}"
      state: present
    notify:
    - restart apche  
  - name: install pgp package
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ php_packages }}"
     notify:
    - restart apache 
  - name:
    template:
      src: ./templates/info.php.j2
      dest: /var/www/html/info.php 
    notify:
    - restart apache             
  handlers:
    name: restart apache
    service:
      name: "{{ pack_name }}"
      state: restarted  

